// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ag_service.proto

/*
Package ag is a generated protocol buffer package.

It is generated from these files:
	ag_service.proto

It has these top-level messages:
	User
	RemoteIdentity
	Users
	Void
	RecordRequest
	Assignment
	Submission
	Assignments
	Group
	Course
	Courses
	Enrollment
	EnrollmentRequest
	EnrollmentResponse
	RecordWithStatusRequest
	StatusCode
*/
package ag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Enrollment_Status int32

const (
	Enrollment_None     Enrollment_Status = 0
	Enrollment_Pending  Enrollment_Status = 1
	Enrollment_Rejected Enrollment_Status = 2
	Enrollment_Student  Enrollment_Status = 3
	Enrollment_Teacher  Enrollment_Status = 4
)

var Enrollment_Status_name = map[int32]string{
	0: "None",
	1: "Pending",
	2: "Rejected",
	3: "Student",
	4: "Teacher",
}
var Enrollment_Status_value = map[string]int32{
	"None":     0,
	"Pending":  1,
	"Rejected": 2,
	"Student":  3,
	"Teacher":  4,
}

func (x Enrollment_Status) String() string {
	return proto.EnumName(Enrollment_Status_name, int32(x))
}
func (Enrollment_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

type User struct {
	ID               uint64            `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	IsAdmin          bool              `protobuf:"varint,2,opt,name=isAdmin" json:"isAdmin,omitempty"`
	Name             string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	StudentID        string            `protobuf:"bytes,4,opt,name=studentID" json:"studentID,omitempty"`
	Email            string            `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	AvatarURL        string            `protobuf:"bytes,6,opt,name=avatarURL" json:"avatarURL,omitempty"`
	RemoteIdentities []*RemoteIdentity `protobuf:"bytes,7,rep,name=remoteIdentities" json:"remoteIdentities,omitempty"`
	Enrollments      []*Enrollment     `protobuf:"bytes,8,rep,name=enrollments" json:"enrollments,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetStudentID() string {
	if m != nil {
		return m.StudentID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *User) GetRemoteIdentities() []*RemoteIdentity {
	if m != nil {
		return m.RemoteIdentities
	}
	return nil
}

func (m *User) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

type RemoteIdentity struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	// gorm:"unique_index:uid_provider_remote_id"
	Provider string `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	// gorm:"unique_index:uid_provider_remote_id"
	RemoteID uint64 `protobuf:"varint,3,opt,name=remoteID" json:"remoteID,omitempty"`
	// TODO: should this be included here?
	AccessToken string `protobuf:"bytes,4,opt,name=accessToken" json:"accessToken,omitempty"`
	UserID      uint64 `protobuf:"varint,5,opt,name=userID" json:"userID,omitempty"`
}

func (m *RemoteIdentity) Reset()                    { *m = RemoteIdentity{} }
func (m *RemoteIdentity) String() string            { return proto.CompactTextString(m) }
func (*RemoteIdentity) ProtoMessage()               {}
func (*RemoteIdentity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RemoteIdentity) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RemoteIdentity) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *RemoteIdentity) GetRemoteID() uint64 {
	if m != nil {
		return m.RemoteID
	}
	return 0
}

func (m *RemoteIdentity) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RemoteIdentity) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Users struct {
	Users []*User `protobuf:"bytes,1,rep,name=Users" json:"Users,omitempty"`
}

func (m *Users) Reset()                    { *m = Users{} }
func (m *Users) String() string            { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()               {}
func (*Users) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// RecordRequest is used to make request for a single record for various datatypes
// such as User, Course, Assignment etc.
type RecordRequest struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *RecordRequest) Reset()                    { *m = RecordRequest{} }
func (m *RecordRequest) String() string            { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()               {}
func (*RecordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RecordRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Assignment struct {
	ID          uint64                     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	CourseID    uint64                     `protobuf:"varint,2,opt,name=courseID" json:"courseID,omitempty"`
	Name        string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Language    string                     `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Deadline    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=deadline" json:"deadline,omitempty"`
	AutoApprove bool                       `protobuf:"varint,6,opt,name=autoApprove" json:"autoApprove,omitempty"`
	Order       uint32                     `protobuf:"varint,7,opt,name=order" json:"order,omitempty"`
	Submission  *Submission                `protobuf:"bytes,8,opt,name=submission" json:"submission,omitempty"`
}

func (m *Assignment) Reset()                    { *m = Assignment{} }
func (m *Assignment) String() string            { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()               {}
func (*Assignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Assignment) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Assignment) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Assignment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Assignment) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Assignment) GetDeadline() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *Assignment) GetAutoApprove() bool {
	if m != nil {
		return m.AutoApprove
	}
	return false
}

func (m *Assignment) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Assignment) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type Submission struct {
	ID           uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	AssignmentID uint64 `protobuf:"varint,2,opt,name=assignmentID" json:"assignmentID,omitempty"`
	UserID       uint64 `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	GroupID      uint64 `protobuf:"varint,4,opt,name=groupID" json:"groupID,omitempty"`
	Score        uint32 `protobuf:"varint,5,opt,name=score" json:"score,omitempty"`
	Scoreobjects string `protobuf:"bytes,6,opt,name=scoreobjects" json:"scoreobjects,omitempty"`
	Buildinfo    string `protobuf:"bytes,7,opt,name=buildinfo" json:"buildinfo,omitempty"`
	Commithash   string `protobuf:"bytes,8,opt,name=commithash" json:"commithash,omitempty"`
}

func (m *Submission) Reset()                    { *m = Submission{} }
func (m *Submission) String() string            { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()               {}
func (*Submission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Submission) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Submission) GetAssignmentID() uint64 {
	if m != nil {
		return m.AssignmentID
	}
	return 0
}

func (m *Submission) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Submission) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Submission) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Submission) GetScoreobjects() string {
	if m != nil {
		return m.Scoreobjects
	}
	return ""
}

func (m *Submission) GetBuildinfo() string {
	if m != nil {
		return m.Buildinfo
	}
	return ""
}

func (m *Submission) GetCommithash() string {
	if m != nil {
		return m.Commithash
	}
	return ""
}

type Assignments struct {
	Assignments []*Assignment `protobuf:"bytes,1,rep,name=assignments" json:"assignments,omitempty"`
}

func (m *Assignments) Reset()                    { *m = Assignments{} }
func (m *Assignments) String() string            { return proto.CompactTextString(m) }
func (*Assignments) ProtoMessage()               {}
func (*Assignments) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Assignments) GetAssignments() []*Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type Group struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	// group name under the same course must be unique
	// gorm:"unique_index:idx_unique_group_name"
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status uint32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	// gorm:"unique_index:idx_unique_group_name"
	CourseID    uint64        `protobuf:"varint,4,opt,name=CourseID" json:"CourseID,omitempty"`
	Users       []*User       `protobuf:"bytes,5,rep,name=Users" json:"Users,omitempty"`
	Enrollments []*Enrollment `protobuf:"bytes,6,rep,name=Enrollments" json:"Enrollments,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Group) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Group) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Group) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Group) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

type Course struct {
	ID          uint64            `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code        string            `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Year        uint32            `protobuf:"varint,4,opt,name=year" json:"year,omitempty"`
	Tag         string            `protobuf:"bytes,5,opt,name=tag" json:"tag,omitempty"`
	Provider    string            `protobuf:"bytes,6,opt,name=provider" json:"provider,omitempty"`
	DirectoryID uint64            `protobuf:"varint,7,opt,name=directoryID" json:"directoryID,omitempty"`
	Enrolled    Enrollment_Status `protobuf:"varint,8,opt,name=enrolled,enum=ag.Enrollment_Status" json:"enrolled,omitempty"`
	Enrollments []*Enrollment     `protobuf:"bytes,9,rep,name=enrollments" json:"enrollments,omitempty"`
	Assignments []*Assignment     `protobuf:"bytes,10,rep,name=assignments" json:"assignments,omitempty"`
	Groups      []*Group          `protobuf:"bytes,11,rep,name=groups" json:"groups,omitempty"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Course) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Course) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Course) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Course) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Course) GetDirectoryID() uint64 {
	if m != nil {
		return m.DirectoryID
	}
	return 0
}

func (m *Course) GetEnrolled() Enrollment_Status {
	if m != nil {
		return m.Enrolled
	}
	return Enrollment_None
}

func (m *Course) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

func (m *Course) GetAssignments() []*Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

func (m *Course) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Courses struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=Courses" json:"Courses,omitempty"`
}

func (m *Courses) Reset()                    { *m = Courses{} }
func (m *Courses) String() string            { return proto.CompactTextString(m) }
func (*Courses) ProtoMessage()               {}
func (*Courses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Courses) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Enrollment struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	// gorm:"unique_index:uid_user_course"
	CourseID uint64 `protobuf:"varint,2,opt,name=courseID" json:"courseID,omitempty"`
	// gorm:"unique_index:uid_user_course"
	UserID  uint64            `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	GroupID uint64            `protobuf:"varint,4,opt,name=groupID" json:"groupID,omitempty"`
	User    *User             `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Course  *Course           `protobuf:"bytes,6,opt,name=course" json:"course,omitempty"`
	Group   *Group            `protobuf:"bytes,7,opt,name=group" json:"group,omitempty"`
	Status  Enrollment_Status `protobuf:"varint,8,opt,name=status,enum=ag.Enrollment_Status" json:"status,omitempty"`
}

func (m *Enrollment) Reset()                    { *m = Enrollment{} }
func (m *Enrollment) String() string            { return proto.CompactTextString(m) }
func (*Enrollment) ProtoMessage()               {}
func (*Enrollment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Enrollment) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Enrollment) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Enrollment) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Enrollment) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Enrollment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Enrollment) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *Enrollment) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *Enrollment) GetStatus() Enrollment_Status {
	if m != nil {
		return m.Status
	}
	return Enrollment_None
}

// EnrollmentRequest is used to create and update enrollments.
// When used to create enrollment, the enrolled field is ignored.
// Only teachers and admins can enroll students.
type EnrollmentRequest struct {
	UserID   uint64            `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	CourseID uint64            `protobuf:"varint,2,opt,name=courseID" json:"courseID,omitempty"`
	Enrolled Enrollment_Status `protobuf:"varint,3,opt,name=enrolled,enum=ag.Enrollment_Status" json:"enrolled,omitempty"`
}

func (m *EnrollmentRequest) Reset()                    { *m = EnrollmentRequest{} }
func (m *EnrollmentRequest) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentRequest) ProtoMessage()               {}
func (*EnrollmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *EnrollmentRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *EnrollmentRequest) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *EnrollmentRequest) GetEnrolled() Enrollment_Status {
	if m != nil {
		return m.Enrolled
	}
	return Enrollment_None
}

type EnrollmentResponse struct {
	Enrollments []*Enrollment `protobuf:"bytes,1,rep,name=enrollments" json:"enrollments,omitempty"`
}

func (m *EnrollmentResponse) Reset()                    { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()               {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *EnrollmentResponse) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

type RecordWithStatusRequest struct {
	ID       uint64              `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Statuses []Enrollment_Status `protobuf:"varint,2,rep,packed,name=statuses,enum=ag.Enrollment_Status" json:"statuses,omitempty"`
}

func (m *RecordWithStatusRequest) Reset()                    { *m = RecordWithStatusRequest{} }
func (m *RecordWithStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*RecordWithStatusRequest) ProtoMessage()               {}
func (*RecordWithStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RecordWithStatusRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RecordWithStatusRequest) GetStatuses() []Enrollment_Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type StatusCode struct {
	Statuscode int32 `protobuf:"varint,1,opt,name=statuscode" json:"statuscode,omitempty"`
}

func (m *StatusCode) Reset()                    { *m = StatusCode{} }
func (m *StatusCode) String() string            { return proto.CompactTextString(m) }
func (*StatusCode) ProtoMessage()               {}
func (*StatusCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *StatusCode) GetStatuscode() int32 {
	if m != nil {
		return m.Statuscode
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "ag.User")
	proto.RegisterType((*RemoteIdentity)(nil), "ag.RemoteIdentity")
	proto.RegisterType((*Users)(nil), "ag.Users")
	proto.RegisterType((*Void)(nil), "ag.Void")
	proto.RegisterType((*RecordRequest)(nil), "ag.RecordRequest")
	proto.RegisterType((*Assignment)(nil), "ag.Assignment")
	proto.RegisterType((*Submission)(nil), "ag.Submission")
	proto.RegisterType((*Assignments)(nil), "ag.Assignments")
	proto.RegisterType((*Group)(nil), "ag.Group")
	proto.RegisterType((*Course)(nil), "ag.Course")
	proto.RegisterType((*Courses)(nil), "ag.Courses")
	proto.RegisterType((*Enrollment)(nil), "ag.Enrollment")
	proto.RegisterType((*EnrollmentRequest)(nil), "ag.EnrollmentRequest")
	proto.RegisterType((*EnrollmentResponse)(nil), "ag.EnrollmentResponse")
	proto.RegisterType((*RecordWithStatusRequest)(nil), "ag.RecordWithStatusRequest")
	proto.RegisterType((*StatusCode)(nil), "ag.StatusCode")
	proto.RegisterEnum("ag.Enrollment_Status", Enrollment_Status_name, Enrollment_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AutograderService service

type AutograderServiceClient interface {
	GetUser(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*User, error)
	GetUsers(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Users, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error)
	GetCourse(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Course, error)
	UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error)
	GetCourses(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Courses, error)
	GetCoursesWithEnrollment(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*Courses, error)
	GetAssignments(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Assignments, error)
	GetEnrollmentsByCourse(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	CreateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error)
	UpdateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error)
}

type autograderServiceClient struct {
	cc *grpc.ClientConn
}

func NewAutograderServiceClient(cc *grpc.ClientConn) AutograderServiceClient {
	return &autograderServiceClient{cc}
}

func (c *autograderServiceClient) GetUser(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetUsers(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/CreateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCourse(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCourses(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Courses, error) {
	out := new(Courses)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCoursesWithEnrollment(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*Courses, error) {
	out := new(Courses)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCoursesWithEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetAssignments(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Assignments, error) {
	out := new(Assignments)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetAssignments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetEnrollmentsByCourse(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	out := new(EnrollmentResponse)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetEnrollmentsByCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) CreateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := grpc.Invoke(ctx, "/ag.AutograderService/CreateEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AutograderService service

type AutograderServiceServer interface {
	GetUser(context.Context, *RecordRequest) (*User, error)
	GetUsers(context.Context, *Void) (*Users, error)
	UpdateUser(context.Context, *User) (*User, error)
	CreateCourse(context.Context, *Course) (*Course, error)
	GetCourse(context.Context, *RecordRequest) (*Course, error)
	UpdateCourse(context.Context, *Course) (*Course, error)
	GetCourses(context.Context, *Void) (*Courses, error)
	GetCoursesWithEnrollment(context.Context, *RecordWithStatusRequest) (*Courses, error)
	GetAssignments(context.Context, *RecordRequest) (*Assignments, error)
	GetEnrollmentsByCourse(context.Context, *RecordWithStatusRequest) (*EnrollmentResponse, error)
	CreateEnrollment(context.Context, *EnrollmentRequest) (*StatusCode, error)
	UpdateEnrollment(context.Context, *EnrollmentRequest) (*StatusCode, error)
}

func RegisterAutograderServiceServer(s *grpc.Server, srv AutograderServiceServer) {
	s.RegisterService(&_AutograderService_serviceDesc, srv)
}

func _AutograderService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetUser(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetUsers(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).CreateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCourse(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCourses(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCoursesWithEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWithStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCoursesWithEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCoursesWithEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCoursesWithEnrollment(ctx, req.(*RecordWithStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetAssignments(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetEnrollmentsByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWithStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetEnrollmentsByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetEnrollmentsByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetEnrollmentsByCourse(ctx, req.(*RecordWithStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/CreateEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).CreateEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutograderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ag.AutograderService",
	HandlerType: (*AutograderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _AutograderService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AutograderService_GetUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AutograderService_UpdateUser_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _AutograderService_CreateCourse_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _AutograderService_GetCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _AutograderService_UpdateCourse_Handler,
		},
		{
			MethodName: "GetCourses",
			Handler:    _AutograderService_GetCourses_Handler,
		},
		{
			MethodName: "GetCoursesWithEnrollment",
			Handler:    _AutograderService_GetCoursesWithEnrollment_Handler,
		},
		{
			MethodName: "GetAssignments",
			Handler:    _AutograderService_GetAssignments_Handler,
		},
		{
			MethodName: "GetEnrollmentsByCourse",
			Handler:    _AutograderService_GetEnrollmentsByCourse_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _AutograderService_CreateEnrollment_Handler,
		},
		{
			MethodName: "UpdateEnrollment",
			Handler:    _AutograderService_UpdateEnrollment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ag_service.proto",
}

func init() { proto.RegisterFile("ag_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xe1, 0x6e, 0xe3, 0x44,
	0x10, 0xae, 0x13, 0x27, 0x71, 0x26, 0x6d, 0x49, 0x57, 0x5c, 0xb1, 0xc2, 0xa9, 0xcd, 0xad, 0x40,
	0xe4, 0xc7, 0x91, 0x42, 0x91, 0xee, 0x0f, 0x12, 0xa8, 0x34, 0x77, 0x51, 0x24, 0x04, 0x68, 0xdb,
	0xc2, 0x1f, 0x24, 0xb4, 0x8d, 0xe7, 0x5c, 0x43, 0xe2, 0x0d, 0xde, 0x75, 0xa5, 0xf2, 0x04, 0xfc,
	0xe6, 0x4d, 0x78, 0x08, 0x5e, 0x83, 0x07, 0xe0, 0x09, 0xf8, 0x89, 0x76, 0xd7, 0xb1, 0xd7, 0x69,
	0xd4, 0xde, 0xf1, 0x6f, 0x67, 0xf6, 0xdb, 0xf1, 0xce, 0x37, 0xdf, 0xcc, 0x1a, 0xfa, 0x3c, 0xfe,
	0x49, 0x62, 0x76, 0x9b, 0xcc, 0x71, 0xbc, 0xca, 0x84, 0x12, 0xa4, 0xc1, 0xe3, 0xc1, 0x71, 0x2c,
	0x44, 0xbc, 0xc0, 0x13, 0xe3, 0xb9, 0xce, 0x5f, 0x9f, 0xa8, 0x64, 0x89, 0x52, 0xf1, 0xe5, 0xca,
	0x82, 0xe8, 0xef, 0x0d, 0xf0, 0xaf, 0x24, 0x66, 0x64, 0x1f, 0x1a, 0xb3, 0x49, 0xe8, 0x0d, 0xbd,
	0x91, 0xcf, 0x1a, 0xb3, 0x09, 0x09, 0xa1, 0x93, 0xc8, 0xb3, 0x68, 0x99, 0xa4, 0x61, 0x63, 0xe8,
	0x8d, 0x02, 0xb6, 0x36, 0x09, 0x01, 0x3f, 0xe5, 0x4b, 0x0c, 0x9b, 0x43, 0x6f, 0xd4, 0x65, 0x66,
	0x4d, 0x9e, 0x42, 0x57, 0xaa, 0x3c, 0xc2, 0x54, 0xcd, 0x26, 0xa1, 0x6f, 0x36, 0x2a, 0x07, 0x79,
	0x17, 0x5a, 0xb8, 0xe4, 0xc9, 0x22, 0x6c, 0x99, 0x1d, 0x6b, 0xe8, 0x33, 0xfc, 0x96, 0x2b, 0x9e,
	0x5d, 0xb1, 0xaf, 0xc3, 0xb6, 0x3d, 0x53, 0x3a, 0xc8, 0x17, 0xd0, 0xcf, 0x70, 0x29, 0x14, 0xce,
	0x74, 0x90, 0x44, 0x25, 0x28, 0xc3, 0xce, 0xb0, 0x39, 0xea, 0x9d, 0x92, 0x31, 0x8f, 0xc7, 0xcc,
	0xdd, 0xbb, 0x63, 0xf7, 0xb0, 0xe4, 0x13, 0xe8, 0x61, 0x9a, 0x89, 0xc5, 0x62, 0x89, 0xa9, 0x92,
	0x61, 0x60, 0x8e, 0xee, 0xeb, 0xa3, 0x2f, 0x4b, 0x37, 0x73, 0x21, 0xf4, 0x0f, 0x0f, 0xf6, 0xeb,
	0x61, 0xef, 0x91, 0x32, 0x80, 0x60, 0x95, 0x89, 0xdb, 0x24, 0xc2, 0xcc, 0xb0, 0xd2, 0x65, 0xa5,
	0xad, 0xf7, 0x8a, 0x4b, 0x4c, 0x0c, 0x35, 0x3e, 0x2b, 0x6d, 0x32, 0x84, 0x1e, 0x9f, 0xcf, 0x51,
	0xca, 0x4b, 0xf1, 0x0b, 0xa6, 0x05, 0x41, 0xae, 0x8b, 0x1c, 0x42, 0x3b, 0x97, 0x98, 0xcd, 0x26,
	0x86, 0x23, 0x9f, 0x15, 0x16, 0xfd, 0x08, 0x5a, 0xba, 0x3c, 0x92, 0x1c, 0x15, 0x8b, 0xd0, 0x33,
	0x99, 0x04, 0x3a, 0x13, 0xed, 0x60, 0xd6, 0x4d, 0xdb, 0xe0, 0x7f, 0x2f, 0x92, 0x88, 0x1e, 0xc3,
	0x1e, 0xc3, 0xb9, 0xc8, 0x22, 0x86, 0xbf, 0xe6, 0x28, 0xd5, 0x66, 0x0e, 0xba, 0xe2, 0x70, 0x26,
	0x65, 0x12, 0xa7, 0x3a, 0xed, 0x6d, 0x29, 0xce, 0x45, 0x9e, 0x49, 0x9d, 0x46, 0xc3, 0xa6, 0xb1,
	0xb6, 0xb7, 0x56, 0x7e, 0x00, 0xc1, 0x82, 0xa7, 0x71, 0xce, 0x63, 0x2c, 0xf2, 0x2a, 0x6d, 0xf2,
	0x02, 0x82, 0x08, 0x79, 0xb4, 0x48, 0x52, 0x34, 0x69, 0xf5, 0x4e, 0x07, 0x63, 0x2b, 0xc8, 0xf1,
	0x5a, 0x90, 0xe3, 0xcb, 0xb5, 0x20, 0x59, 0x89, 0x35, 0x74, 0xe5, 0x4a, 0x9c, 0xad, 0x34, 0xb9,
	0x68, 0xb4, 0x11, 0x30, 0xd7, 0xa5, 0x15, 0x25, 0x32, 0x5d, 0x85, 0xce, 0xd0, 0x1b, 0xed, 0x31,
	0x6b, 0x90, 0x31, 0x80, 0xcc, 0xaf, 0x97, 0x89, 0x94, 0x89, 0x48, 0xc3, 0xc0, 0x7c, 0xd1, 0x94,
	0xfc, 0xa2, 0xf4, 0x32, 0x07, 0x41, 0xff, 0xf1, 0x00, 0xaa, 0xad, 0x7b, 0x54, 0x50, 0xd8, 0xe5,
	0x25, 0x51, 0x25, 0x1d, 0x35, 0x9f, 0x53, 0xb7, 0xa6, 0x5b, 0x37, 0xdd, 0x3e, 0x71, 0x26, 0xf2,
	0x55, 0xd1, 0x0e, 0x3e, 0x5b, 0x9b, 0xfa, 0xea, 0x72, 0x2e, 0x32, 0xcb, 0xc8, 0x1e, 0xb3, 0x86,
	0xfe, 0x96, 0x59, 0x88, 0xeb, 0x9f, 0x71, 0xae, 0x64, 0xd1, 0x0f, 0x35, 0x9f, 0x6e, 0x98, 0xeb,
	0x3c, 0x59, 0x44, 0x49, 0xfa, 0x5a, 0x98, 0xc4, 0xbb, 0xac, 0x72, 0x90, 0x23, 0x80, 0xb9, 0x58,
	0x2e, 0x13, 0x75, 0xc3, 0xe5, 0x8d, 0x49, 0xbe, 0xcb, 0x1c, 0x0f, 0xfd, 0x12, 0x7a, 0x55, 0xd9,
	0x4d, 0x7f, 0x54, 0x89, 0xac, 0x55, 0x65, 0xc8, 0xaa, 0x50, 0xcc, 0x85, 0xd0, 0x3f, 0x3d, 0x68,
	0x4d, 0x75, 0x12, 0xf7, 0x88, 0x5a, 0xeb, 0xa2, 0xe1, 0xe8, 0xe2, 0x10, 0xda, 0x52, 0x71, 0x95,
	0x4b, 0x43, 0xcc, 0x1e, 0x2b, 0x2c, 0xad, 0x97, 0xf3, 0xb5, 0xbe, 0x2c, 0x33, 0xa5, 0x5d, 0x69,
	0xbc, 0xb5, 0x55, 0xe3, 0xfa, 0xce, 0x2f, 0x9d, 0x9e, 0x6e, 0x6f, 0xef, 0x69, 0x07, 0x42, 0xff,
	0x6e, 0x40, 0xdb, 0x86, 0x7f, 0xa3, 0x4b, 0x13, 0xf0, 0xe7, 0x22, 0x2a, 0x05, 0xae, 0xd7, 0xda,
	0x77, 0x87, 0x3c, 0x33, 0x97, 0xdd, 0x63, 0x66, 0x4d, 0xfa, 0xd0, 0x54, 0x3c, 0x2e, 0xc6, 0x99,
	0x5e, 0xd6, 0x26, 0x43, 0x7b, 0x63, 0x32, 0x0c, 0xa1, 0x17, 0x25, 0x19, 0xce, 0x95, 0xc8, 0xee,
	0x66, 0x13, 0x53, 0x39, 0x9f, 0xb9, 0x2e, 0xf2, 0x29, 0x04, 0x76, 0x12, 0x61, 0x64, 0x2a, 0xb7,
	0x7f, 0xfa, 0xa4, 0x9e, 0xd5, 0xf8, 0xc2, 0xb0, 0xc7, 0x4a, 0xd8, 0xe6, 0x7c, 0xeb, 0x3e, 0x3a,
	0xdf, 0x36, 0x2b, 0x0e, 0x8f, 0x56, 0x9c, 0x3c, 0x83, 0xb6, 0x51, 0xad, 0x0c, 0x7b, 0x06, 0xdc,
	0xd5, 0x60, 0x23, 0x01, 0x56, 0x6c, 0xd0, 0x13, 0xe8, 0x58, 0x7e, 0x25, 0xf9, 0xa0, 0x5c, 0x16,
	0x6a, 0x02, 0x0d, 0xb7, 0x2e, 0xb6, 0xde, 0xa2, 0x7f, 0x35, 0x00, 0xaa, 0x1b, 0xbe, 0xd5, 0xf8,
	0x79, 0xfb, 0x5e, 0x7b, 0x0a, 0xbe, 0xc6, 0x14, 0xc3, 0xa7, 0xd2, 0x93, 0xf1, 0x12, 0x0a, 0x6d,
	0x1b, 0xdb, 0x54, 0xac, 0x7e, 0xdf, 0x62, 0x87, 0x1c, 0x43, 0xcb, 0x04, 0x33, 0x55, 0xab, 0x31,
	0x60, 0xfd, 0xe4, 0xe3, 0x52, 0xe7, 0x0f, 0x16, 0xae, 0x00, 0xd1, 0x29, 0xb4, 0xad, 0x87, 0x04,
	0xe0, 0x7f, 0x23, 0x52, 0xec, 0xef, 0x90, 0x1e, 0x74, 0xbe, 0xc3, 0x34, 0x4a, 0xd2, 0xb8, 0xef,
	0x91, 0x5d, 0x08, 0x18, 0xea, 0x7e, 0xc7, 0xa8, 0xdf, 0xd0, 0x5b, 0x17, 0xf6, 0x19, 0xed, 0x37,
	0xb5, 0x71, 0x89, 0x7c, 0x7e, 0x83, 0x59, 0xdf, 0xa7, 0xbf, 0xc1, 0x81, 0x53, 0xe8, 0x62, 0xd6,
	0x57, 0x0c, 0x79, 0x35, 0x86, 0x1e, 0x62, 0xd5, 0xd5, 0x5e, 0xf3, 0x8d, 0xb4, 0x47, 0x5f, 0x01,
	0x71, 0xbf, 0x2d, 0x57, 0x22, 0x95, 0xb8, 0xa9, 0x48, 0xef, 0xf1, 0x17, 0xf7, 0x47, 0x78, 0xcf,
	0xbe, 0x55, 0x3f, 0x24, 0xea, 0xa6, 0xf8, 0xca, 0xf6, 0x57, 0x4b, 0xdf, 0xd2, 0x32, 0x88, 0x32,
	0x6c, 0x0c, 0x9b, 0x0f, 0xdc, 0x72, 0x0d, 0xa3, 0xcf, 0x01, 0xac, 0xef, 0x5c, 0xb7, 0xf1, 0x11,
	0x80, 0xdd, 0x31, 0x0d, 0xae, 0x03, 0xb7, 0x98, 0xe3, 0x39, 0xfd, 0xd7, 0x87, 0x83, 0xb3, 0x5c,
	0x89, 0x38, 0xe3, 0x11, 0x66, 0x17, 0xf6, 0x4f, 0x8a, 0x8c, 0xa0, 0x33, 0x45, 0x65, 0x7e, 0x90,
	0x0e, 0xec, 0x6f, 0x87, 0xf3, 0xb4, 0x0e, 0x4a, 0x41, 0xd1, 0x1d, 0xf2, 0x0c, 0x82, 0x02, 0x29,
	0x89, 0xf1, 0xeb, 0xd7, 0x78, 0xd0, 0x5d, 0x23, 0x24, 0xdd, 0x21, 0x14, 0xe0, 0x6a, 0x15, 0x71,
	0x85, 0x26, 0x5e, 0x79, 0xb8, 0x16, 0x66, 0x04, 0xbb, 0xe7, 0x19, 0x72, 0x85, 0xc5, 0xd4, 0x72,
	0x34, 0x39, 0x70, 0xd6, 0x74, 0x87, 0x3c, 0x87, 0xee, 0x14, 0x55, 0x01, 0xdb, 0x72, 0xb9, 0x3a,
	0x7a, 0x04, 0xbb, 0xf6, 0xdb, 0x8f, 0xc6, 0xfd, 0x10, 0xa0, 0x8c, 0xeb, 0xa6, 0xd2, 0xab, 0x50,
	0x3a, 0x99, 0x57, 0x10, 0x56, 0x30, 0x5d, 0x3f, 0xa7, 0xa9, 0xdf, 0xaf, 0x6e, 0x73, 0xaf, 0xb2,
	0x9b, 0x71, 0x5e, 0xc0, 0xfe, 0x14, 0x95, 0xfb, 0x32, 0x6d, 0xc9, 0xe5, 0x9d, 0xfa, 0x94, 0xd2,
	0xe7, 0xbe, 0x85, 0xc3, 0x29, 0x2a, 0x67, 0xd6, 0x7f, 0x75, 0x57, 0xa4, 0xf6, 0xe0, 0xd7, 0x0f,
	0x37, 0xf4, 0x58, 0x88, 0x97, 0xee, 0x90, 0xcf, 0xa1, 0x6f, 0x99, 0x77, 0x12, 0x79, 0xb2, 0x89,
	0xb6, 0x41, 0xec, 0x3f, 0x45, 0xa9, 0x2d, 0x7b, 0xd8, 0xd2, 0xfb, 0x3f, 0x0e, 0x5f, 0xb7, 0xcd,
	0xcf, 0xd0, 0x67, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x0f, 0x14, 0xeb, 0xc3, 0x0b, 0x00,
	0x00,
}
