// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ag_service.proto

/*
Package ag is a generated protocol buffer package.

It is generated from these files:
	ag_service.proto

It has these top-level messages:
	User
	RemoteIdentity
	Users
	Assignment
	Submission
	Assignments
	Group
	Course
	Courses
	Enrollment
	EnrollmentRequest
	EnrollmentResponse
	RecordRequest
	RecordWithStatusRequest
	Void
	StatusCode
*/
package ag

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Enrollment_Status int32

const (
	Enrollment_None     Enrollment_Status = 0
	Enrollment_Pending  Enrollment_Status = 1
	Enrollment_Rejected Enrollment_Status = 2
	Enrollment_Student  Enrollment_Status = 3
	Enrollment_Teacher  Enrollment_Status = 4
)

var Enrollment_Status_name = map[int32]string{
	0: "None",
	1: "Pending",
	2: "Rejected",
	3: "Student",
	4: "Teacher",
}
var Enrollment_Status_value = map[string]int32{
	"None":     0,
	"Pending":  1,
	"Rejected": 2,
	"Student":  3,
	"Teacher":  4,
}

func (x Enrollment_Status) String() string {
	return proto.EnumName(Enrollment_Status_name, int32(x))
}
func (Enrollment_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorAgService, []int{9, 0} }

type User struct {
	ID               uint64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsAdmin          bool              `protobuf:"varint,2,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	Name             string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StudentID        string            `protobuf:"bytes,4,opt,name=studentID,proto3" json:"studentID,omitempty"`
	Email            string            `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AvatarURL        string            `protobuf:"bytes,6,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
	RemoteIdentities []*RemoteIdentity `protobuf:"bytes,7,rep,name=remoteIdentities" json:"remoteIdentities,omitempty"`
	Enrollments      []*Enrollment     `protobuf:"bytes,8,rep,name=enrollments" json:"enrollments,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{0} }

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetStudentID() string {
	if m != nil {
		return m.StudentID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *User) GetRemoteIdentities() []*RemoteIdentity {
	if m != nil {
		return m.RemoteIdentities
	}
	return nil
}

func (m *User) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

type RemoteIdentity struct {
	ID       uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty" gorm:"unique_index:uid_provider_remote_id"`
	RemoteID uint64 `protobuf:"varint,3,opt,name=remoteID,proto3" json:"remoteID,omitempty" gorm:"unique_index:uid_provider_remote_id"`
	// TODO: should the accessToken be included here?
	AccessToken string `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	UserID      uint64 `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (m *RemoteIdentity) Reset()                    { *m = RemoteIdentity{} }
func (m *RemoteIdentity) String() string            { return proto.CompactTextString(m) }
func (*RemoteIdentity) ProtoMessage()               {}
func (*RemoteIdentity) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{1} }

func (m *RemoteIdentity) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RemoteIdentity) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *RemoteIdentity) GetRemoteID() uint64 {
	if m != nil {
		return m.RemoteID
	}
	return 0
}

func (m *RemoteIdentity) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RemoteIdentity) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Users struct {
	Users []*User `protobuf:"bytes,1,rep,name=Users" json:"Users,omitempty"`
}

func (m *Users) Reset()                    { *m = Users{} }
func (m *Users) String() string            { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()               {}
func (*Users) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{2} }

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Assignment struct {
	ID          uint64                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CourseID    uint64                     `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty"`
	Name        string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language    string                     `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Deadline    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=deadline" json:"deadline,omitempty"`
	AutoApprove bool                       `protobuf:"varint,6,opt,name=autoApprove,proto3" json:"autoApprove,omitempty"`
	Order       uint32                     `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	Submission  *Submission                `protobuf:"bytes,8,opt,name=submission" json:"submission,omitempty"`
}

func (m *Assignment) Reset()                    { *m = Assignment{} }
func (m *Assignment) String() string            { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()               {}
func (*Assignment) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{3} }

func (m *Assignment) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Assignment) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Assignment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Assignment) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Assignment) GetDeadline() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *Assignment) GetAutoApprove() bool {
	if m != nil {
		return m.AutoApprove
	}
	return false
}

func (m *Assignment) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Assignment) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type Submission struct {
	ID           uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AssignmentID uint64 `protobuf:"varint,2,opt,name=assignmentID,proto3" json:"assignmentID,omitempty"`
	UserID       uint64 `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	GroupID      uint64 `protobuf:"varint,4,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Score        uint32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Scoreobjects string `protobuf:"bytes,6,opt,name=scoreobjects,proto3" json:"scoreobjects,omitempty"`
	Buildinfo    string `protobuf:"bytes,7,opt,name=buildinfo,proto3" json:"buildinfo,omitempty"`
	Commithash   string `protobuf:"bytes,8,opt,name=commithash,proto3" json:"commithash,omitempty"`
}

func (m *Submission) Reset()                    { *m = Submission{} }
func (m *Submission) String() string            { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()               {}
func (*Submission) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{4} }

func (m *Submission) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Submission) GetAssignmentID() uint64 {
	if m != nil {
		return m.AssignmentID
	}
	return 0
}

func (m *Submission) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Submission) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Submission) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Submission) GetScoreobjects() string {
	if m != nil {
		return m.Scoreobjects
	}
	return ""
}

func (m *Submission) GetBuildinfo() string {
	if m != nil {
		return m.Buildinfo
	}
	return ""
}

func (m *Submission) GetCommithash() string {
	if m != nil {
		return m.Commithash
	}
	return ""
}

type Assignments struct {
	Assignments []*Assignment `protobuf:"bytes,1,rep,name=assignments" json:"assignments,omitempty"`
}

func (m *Assignments) Reset()                    { *m = Assignments{} }
func (m *Assignments) String() string            { return proto.CompactTextString(m) }
func (*Assignments) ProtoMessage()               {}
func (*Assignments) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{5} }

func (m *Assignments) GetAssignments() []*Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type Group struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// group name under the same course must be unique
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"unique_index:idx_unique_group_name"`
	CourseID    uint64            `protobuf:"varint,3,opt,name=CourseID,proto3" json:"CourseID,omitempty" gorm:"unique_index:idx_unique_group_name"`
	Status      Enrollment_Status `protobuf:"varint,4,opt,name=status,proto3,enum=ag.Enrollment_Status" json:"status,omitempty"`
	Users       []*User           `protobuf:"bytes,5,rep,name=Users" json:"Users,omitempty"`
	Enrollments []*Enrollment     `protobuf:"bytes,6,rep,name=Enrollments" json:"Enrollments,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{6} }

func (m *Group) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Group) GetStatus() Enrollment_Status {
	if m != nil {
		return m.Status
	}
	return Enrollment_None
}

func (m *Group) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Group) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

type Course struct {
	ID          uint64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code        string            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Year        uint32            `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Tag         string            `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Provider    string            `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	DirectoryID uint64            `protobuf:"varint,7,opt,name=directoryID,proto3" json:"directoryID,omitempty"`
	Enrolled    Enrollment_Status `protobuf:"varint,8,opt,name=enrolled,proto3,enum=ag.Enrollment_Status" json:"enrolled,omitempty"`
	Enrollments []*Enrollment     `protobuf:"bytes,9,rep,name=enrollments" json:"enrollments,omitempty"`
	Assignments []*Assignment     `protobuf:"bytes,10,rep,name=assignments" json:"assignments,omitempty"`
	Groups      []*Group          `protobuf:"bytes,11,rep,name=groups" json:"groups,omitempty"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{7} }

func (m *Course) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Course) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Course) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Course) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Course) GetDirectoryID() uint64 {
	if m != nil {
		return m.DirectoryID
	}
	return 0
}

func (m *Course) GetEnrolled() Enrollment_Status {
	if m != nil {
		return m.Enrolled
	}
	return Enrollment_None
}

func (m *Course) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

func (m *Course) GetAssignments() []*Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

func (m *Course) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Courses struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=Courses" json:"Courses,omitempty"`
}

func (m *Courses) Reset()                    { *m = Courses{} }
func (m *Courses) String() string            { return proto.CompactTextString(m) }
func (*Courses) ProtoMessage()               {}
func (*Courses) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{8} }

func (m *Courses) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Enrollment struct {
	ID       uint64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CourseID uint64            `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty" gorm:"unique_index:uid_user_course"`
	UserID   uint64            `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty" gorm:"unique_index:uid_user_course"`
	GroupID  uint64            `protobuf:"varint,4,opt,name=groupID,proto3" json:"groupID,omitempty"`
	User     *User             `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Course   *Course           `protobuf:"bytes,6,opt,name=course" json:"course,omitempty"`
	Group    *Group            `protobuf:"bytes,7,opt,name=group" json:"group,omitempty"`
	Status   Enrollment_Status `protobuf:"varint,8,opt,name=status,proto3,enum=ag.Enrollment_Status" json:"status,omitempty"`
}

func (m *Enrollment) Reset()                    { *m = Enrollment{} }
func (m *Enrollment) String() string            { return proto.CompactTextString(m) }
func (*Enrollment) ProtoMessage()               {}
func (*Enrollment) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{9} }

func (m *Enrollment) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Enrollment) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *Enrollment) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Enrollment) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Enrollment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Enrollment) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *Enrollment) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *Enrollment) GetStatus() Enrollment_Status {
	if m != nil {
		return m.Status
	}
	return Enrollment_None
}

// EnrollmentRequest is used to create and update enrollments.
// When used to create enrollment, the enrolled field is ignored.
// Only teachers and admins can enroll students.
type EnrollmentRequest struct {
	UserID   uint64            `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CourseID uint64            `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty"`
	Enrolled Enrollment_Status `protobuf:"varint,3,opt,name=enrolled,proto3,enum=ag.Enrollment_Status" json:"enrolled,omitempty"`
}

func (m *EnrollmentRequest) Reset()                    { *m = EnrollmentRequest{} }
func (m *EnrollmentRequest) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentRequest) ProtoMessage()               {}
func (*EnrollmentRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{10} }

func (m *EnrollmentRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *EnrollmentRequest) GetCourseID() uint64 {
	if m != nil {
		return m.CourseID
	}
	return 0
}

func (m *EnrollmentRequest) GetEnrolled() Enrollment_Status {
	if m != nil {
		return m.Enrolled
	}
	return Enrollment_None
}

type EnrollmentResponse struct {
	Enrollments []*Enrollment `protobuf:"bytes,1,rep,name=enrollments" json:"enrollments,omitempty"`
}

func (m *EnrollmentResponse) Reset()                    { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()               {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{11} }

func (m *EnrollmentResponse) GetEnrollments() []*Enrollment {
	if m != nil {
		return m.Enrollments
	}
	return nil
}

// RecordRequest is used to make request for a single record for
// different datatypes such as User, Course, Assignment etc.
// Hence, the ID field can be UserID or CourseID, or some other ID.
type RecordRequest struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *RecordRequest) Reset()                    { *m = RecordRequest{} }
func (m *RecordRequest) String() string            { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()               {}
func (*RecordRequest) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{12} }

func (m *RecordRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// RecordWithStatusRequest is used to make request for records for
// different datatypes such as Courses and EnrollmentResponse.
// Hence, the ID field can be UserID or CourseID, or some other ID.
//
// TODO This message type can be merged with RecordRequest, since
// all fields are optional, and hence we don't need to use the statuses field.
type RecordWithStatusRequest struct {
	ID       uint64              `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Statuses []Enrollment_Status `protobuf:"varint,2,rep,packed,name=statuses,enum=ag.Enrollment_Status" json:"statuses,omitempty"`
}

func (m *RecordWithStatusRequest) Reset()         { *m = RecordWithStatusRequest{} }
func (m *RecordWithStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RecordWithStatusRequest) ProtoMessage()    {}
func (*RecordWithStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorAgService, []int{13}
}

func (m *RecordWithStatusRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RecordWithStatusRequest) GetStatuses() []Enrollment_Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{14} }

type StatusCode struct {
	Statuscode int32 `protobuf:"varint,1,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
}

func (m *StatusCode) Reset()                    { *m = StatusCode{} }
func (m *StatusCode) String() string            { return proto.CompactTextString(m) }
func (*StatusCode) ProtoMessage()               {}
func (*StatusCode) Descriptor() ([]byte, []int) { return fileDescriptorAgService, []int{15} }

func (m *StatusCode) GetStatuscode() int32 {
	if m != nil {
		return m.Statuscode
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "ag.User")
	proto.RegisterType((*RemoteIdentity)(nil), "ag.RemoteIdentity")
	proto.RegisterType((*Users)(nil), "ag.Users")
	proto.RegisterType((*Assignment)(nil), "ag.Assignment")
	proto.RegisterType((*Submission)(nil), "ag.Submission")
	proto.RegisterType((*Assignments)(nil), "ag.Assignments")
	proto.RegisterType((*Group)(nil), "ag.Group")
	proto.RegisterType((*Course)(nil), "ag.Course")
	proto.RegisterType((*Courses)(nil), "ag.Courses")
	proto.RegisterType((*Enrollment)(nil), "ag.Enrollment")
	proto.RegisterType((*EnrollmentRequest)(nil), "ag.EnrollmentRequest")
	proto.RegisterType((*EnrollmentResponse)(nil), "ag.EnrollmentResponse")
	proto.RegisterType((*RecordRequest)(nil), "ag.RecordRequest")
	proto.RegisterType((*RecordWithStatusRequest)(nil), "ag.RecordWithStatusRequest")
	proto.RegisterType((*Void)(nil), "ag.Void")
	proto.RegisterType((*StatusCode)(nil), "ag.StatusCode")
	proto.RegisterEnum("ag.Enrollment_Status", Enrollment_Status_name, Enrollment_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AutograderService service

type AutograderServiceClient interface {
	GetUser(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*User, error)
	GetUsers(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Users, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error)
	GetCourse(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Course, error)
	UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error)
	GetCourses(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Courses, error)
	GetCoursesWithEnrollment(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*Courses, error)
	GetAssignments(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Assignments, error)
	GetEnrollmentsByCourse(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	CreateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error)
	UpdateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error)
}

type autograderServiceClient struct {
	cc *grpc.ClientConn
}

func NewAutograderServiceClient(cc *grpc.ClientConn) AutograderServiceClient {
	return &autograderServiceClient{cc}
}

func (c *autograderServiceClient) GetUser(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetUsers(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/CreateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCourse(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCourses(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Courses, error) {
	out := new(Courses)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetCoursesWithEnrollment(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*Courses, error) {
	out := new(Courses)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetCoursesWithEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetAssignments(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Assignments, error) {
	out := new(Assignments)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetAssignments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) GetEnrollmentsByCourse(ctx context.Context, in *RecordWithStatusRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	out := new(EnrollmentResponse)
	err := grpc.Invoke(ctx, "/ag.AutograderService/GetEnrollmentsByCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) CreateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := grpc.Invoke(ctx, "/ag.AutograderService/CreateEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autograderServiceClient) UpdateEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := grpc.Invoke(ctx, "/ag.AutograderService/UpdateEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AutograderService service

type AutograderServiceServer interface {
	GetUser(context.Context, *RecordRequest) (*User, error)
	GetUsers(context.Context, *Void) (*Users, error)
	UpdateUser(context.Context, *User) (*User, error)
	CreateCourse(context.Context, *Course) (*Course, error)
	GetCourse(context.Context, *RecordRequest) (*Course, error)
	UpdateCourse(context.Context, *Course) (*Course, error)
	GetCourses(context.Context, *Void) (*Courses, error)
	GetCoursesWithEnrollment(context.Context, *RecordWithStatusRequest) (*Courses, error)
	GetAssignments(context.Context, *RecordRequest) (*Assignments, error)
	GetEnrollmentsByCourse(context.Context, *RecordWithStatusRequest) (*EnrollmentResponse, error)
	CreateEnrollment(context.Context, *EnrollmentRequest) (*StatusCode, error)
	UpdateEnrollment(context.Context, *EnrollmentRequest) (*StatusCode, error)
}

func RegisterAutograderServiceServer(s *grpc.Server, srv AutograderServiceServer) {
	s.RegisterService(&_AutograderService_serviceDesc, srv)
}

func _AutograderService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetUser(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetUsers(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).CreateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCourse(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCourses(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetCoursesWithEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWithStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetCoursesWithEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetCoursesWithEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetCoursesWithEnrollment(ctx, req.(*RecordWithStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetAssignments(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_GetEnrollmentsByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWithStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).GetEnrollmentsByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/GetEnrollmentsByCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).GetEnrollmentsByCourse(ctx, req.(*RecordWithStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/CreateEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).CreateEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutograderService_UpdateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutograderServiceServer).UpdateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ag.AutograderService/UpdateEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutograderServiceServer).UpdateEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutograderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ag.AutograderService",
	HandlerType: (*AutograderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _AutograderService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AutograderService_GetUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AutograderService_UpdateUser_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _AutograderService_CreateCourse_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _AutograderService_GetCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _AutograderService_UpdateCourse_Handler,
		},
		{
			MethodName: "GetCourses",
			Handler:    _AutograderService_GetCourses_Handler,
		},
		{
			MethodName: "GetCoursesWithEnrollment",
			Handler:    _AutograderService_GetCoursesWithEnrollment_Handler,
		},
		{
			MethodName: "GetAssignments",
			Handler:    _AutograderService_GetAssignments_Handler,
		},
		{
			MethodName: "GetEnrollmentsByCourse",
			Handler:    _AutograderService_GetEnrollmentsByCourse_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _AutograderService_CreateEnrollment_Handler,
		},
		{
			MethodName: "UpdateEnrollment",
			Handler:    _AutograderService_UpdateEnrollment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ag_service.proto",
}

func init() { proto.RegisterFile("ag_service.proto", fileDescriptorAgService) }

var fileDescriptorAgService = []byte{
	// 1239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x8e, 0x1b, 0x35,
	0x14, 0xde, 0x24, 0x93, 0xec, 0xe4, 0x64, 0x77, 0x49, 0x2d, 0x5a, 0x46, 0xa1, 0x6a, 0x52, 0x03,
	0x6a, 0x40, 0x6d, 0x16, 0x16, 0xa9, 0x17, 0x45, 0xa2, 0xda, 0x6e, 0xda, 0x28, 0x08, 0x01, 0xf2,
	0xb6, 0x70, 0x83, 0x14, 0x4d, 0x66, 0xdc, 0x59, 0x43, 0x66, 0x9c, 0x8e, 0x3d, 0x55, 0x97, 0x27,
	0xe0, 0x0d, 0x78, 0x03, 0x1e, 0x6b, 0x1f, 0x80, 0xcb, 0xbd, 0xe2, 0x12, 0xd9, 0x9e, 0x1f, 0xe7,
	0xa7, 0xdd, 0x2d, 0x77, 0xf6, 0xf1, 0x77, 0xce, 0x9c, 0xf3, 0xf9, 0x3b, 0x67, 0x0c, 0x5d, 0x3f,
	0x9a, 0x09, 0x9a, 0xbe, 0x66, 0x01, 0x1d, 0x2d, 0x53, 0x2e, 0x39, 0xaa, 0xfb, 0x51, 0xaf, 0x1f,
	0x71, 0x1e, 0x2d, 0xe8, 0xa1, 0xb6, 0xcc, 0xb3, 0x97, 0x87, 0x92, 0xc5, 0x54, 0x48, 0x3f, 0x5e,
	0x1a, 0x50, 0xef, 0x41, 0xc4, 0xe4, 0x59, 0x36, 0x1f, 0x05, 0x3c, 0x3e, 0x8c, 0x78, 0xc4, 0x2b,
	0xa4, 0xda, 0xe9, 0x8d, 0x5e, 0x19, 0x38, 0xfe, 0xb3, 0x0e, 0xce, 0x0b, 0x41, 0x53, 0x74, 0x00,
	0xf5, 0xe9, 0xd8, 0xab, 0x0d, 0x6a, 0x43, 0x87, 0xd4, 0xa7, 0x63, 0xe4, 0xc1, 0x2e, 0x13, 0xc7,
	0x61, 0xcc, 0x12, 0xaf, 0x3e, 0xa8, 0x0d, 0x5d, 0x52, 0x6c, 0x11, 0x02, 0x27, 0xf1, 0x63, 0xea,
	0x35, 0x06, 0xb5, 0x61, 0x9b, 0xe8, 0x35, 0xba, 0x0d, 0x6d, 0x21, 0xb3, 0x90, 0x26, 0x72, 0x3a,
	0xf6, 0x1c, 0x7d, 0x50, 0x19, 0xd0, 0x87, 0xd0, 0xa4, 0xb1, 0xcf, 0x16, 0x5e, 0x53, 0x9f, 0x98,
	0x8d, 0xf2, 0xf1, 0x5f, 0xfb, 0xd2, 0x4f, 0x5f, 0x90, 0xef, 0xbd, 0x96, 0xf1, 0x29, 0x0d, 0xe8,
	0x5b, 0xe8, 0xa6, 0x34, 0xe6, 0x92, 0x4e, 0x55, 0x10, 0x26, 0x19, 0x15, 0xde, 0xee, 0xa0, 0x31,
	0xec, 0x1c, 0xa1, 0x91, 0x1f, 0x8d, 0x88, 0x7d, 0x76, 0x4e, 0x36, 0xb0, 0xe8, 0x4b, 0xe8, 0xd0,
	0x24, 0xe5, 0x8b, 0x45, 0x4c, 0x13, 0x29, 0x3c, 0x57, 0xbb, 0x1e, 0x28, 0xd7, 0xa7, 0xa5, 0x99,
	0xd8, 0x10, 0x7c, 0x59, 0x83, 0x83, 0xd5, 0xb0, 0x1b, 0xa4, 0x7c, 0x07, 0xee, 0x32, 0xe5, 0xaf,
	0x59, 0x48, 0x53, 0xcd, 0x4a, 0xfb, 0xc9, 0xe8, 0xf2, 0xa2, 0xff, 0x45, 0xc4, 0xd3, 0xf8, 0x11,
	0xce, 0x12, 0xf6, 0x2a, 0xa3, 0x33, 0x96, 0x84, 0xf4, 0xcd, 0xa3, 0x8c, 0x85, 0xb3, 0x02, 0x3a,
	0x33, 0xc9, 0xcd, 0x58, 0x88, 0x49, 0xe9, 0xaf, 0x62, 0xe5, 0x49, 0x8f, 0x35, 0x95, 0xce, 0xfb,
	0xc7, 0x2a, 0xfc, 0xd1, 0x00, 0x3a, 0x7e, 0x10, 0x50, 0x21, 0x9e, 0xf3, 0xdf, 0x69, 0x92, 0x5f,
	0x80, 0x6d, 0x42, 0xb7, 0xa0, 0x95, 0x09, 0x9a, 0x4e, 0xc7, 0xfa, 0x0e, 0x1c, 0x92, 0xef, 0xf0,
	0x3d, 0x68, 0xaa, 0xeb, 0x17, 0xe8, 0x4e, 0xbe, 0xf0, 0x6a, 0x9a, 0x29, 0x57, 0x31, 0xa5, 0x0c,
	0xc4, 0x98, 0x95, 0x50, 0xe0, 0x58, 0x08, 0x16, 0x25, 0x8a, 0xad, 0x0d, 0x66, 0x7a, 0xe0, 0x06,
	0x3c, 0x4b, 0x85, 0xaa, 0xa6, 0xae, 0xad, 0xe5, 0x7e, 0xab, 0x60, 0x7a, 0xe0, 0x2e, 0xfc, 0x24,
	0xca, 0xfc, 0x88, 0xe6, 0xe9, 0x96, 0x7b, 0xf4, 0x10, 0xdc, 0x90, 0xfa, 0xe1, 0x82, 0x25, 0x54,
	0x67, 0xdb, 0x39, 0xea, 0x8d, 0x8c, 0xec, 0x47, 0x85, 0x98, 0x47, 0xcf, 0x0b, 0xd9, 0x93, 0x12,
	0xab, 0x59, 0xc8, 0x24, 0x3f, 0x5e, 0x2a, 0xb2, 0xa8, 0x96, 0x94, 0x4b, 0x6c, 0x93, 0x12, 0x22,
	0x4f, 0xd5, 0xe5, 0xed, 0x0e, 0x6a, 0xc3, 0x7d, 0x62, 0x36, 0x68, 0x04, 0x20, 0xb2, 0x79, 0xcc,
	0x84, 0x60, 0x3c, 0xf1, 0x5c, 0xfd, 0x45, 0xad, 0x94, 0xd3, 0xd2, 0x4a, 0x2c, 0x04, 0xfe, 0xa7,
	0x06, 0x50, 0x1d, 0x6d, 0x50, 0x81, 0x61, 0xcf, 0x2f, 0x89, 0x2a, 0xe9, 0x58, 0xb1, 0x59, 0xd7,
	0xd1, 0xb0, 0xaf, 0x43, 0x75, 0x5d, 0x94, 0xf2, 0x6c, 0x99, 0x77, 0x91, 0x43, 0x8a, 0xad, 0x4a,
	0x5d, 0x04, 0x3c, 0x35, 0x8c, 0xec, 0x13, 0xb3, 0x51, 0xdf, 0xd2, 0x0b, 0x3e, 0xff, 0x8d, 0x06,
	0x52, 0xe4, 0x6d, 0xb4, 0x62, 0x53, 0x7d, 0x36, 0xcf, 0xd8, 0x22, 0x64, 0xc9, 0x4b, 0xae, 0x0b,
	0x6f, 0x93, 0xca, 0x80, 0xee, 0x00, 0x04, 0x3c, 0x8e, 0x99, 0x3c, 0xf3, 0xc5, 0x99, 0x2e, 0xbe,
	0x4d, 0x2c, 0x0b, 0x7e, 0x0c, 0x9d, 0xea, 0xda, 0x75, 0x5b, 0x55, 0x85, 0x14, 0x62, 0xd1, 0x64,
	0x55, 0x28, 0x62, 0x43, 0xf0, 0xdf, 0x75, 0x68, 0x4e, 0x54, 0x11, 0x1b, 0x44, 0x1d, 0xe7, 0xba,
	0x30, 0x9d, 0xf4, 0xe0, 0xf2, 0xa2, 0xff, 0xf9, 0x16, 0xf5, 0xb3, 0xf0, 0xcd, 0x2c, 0x37, 0x68,
	0x2e, 0x66, 0xca, 0x07, 0xe7, 0x32, 0x9a, 0x82, 0x7b, 0x52, 0xc8, 0xce, 0x34, 0xd1, 0x7b, 0x86,
	0x29, 0xdd, 0xd1, 0x03, 0x68, 0x09, 0xe9, 0xcb, 0x4c, 0x68, 0xe6, 0x0f, 0x8e, 0x6e, 0xae, 0xce,
	0x8a, 0xd1, 0xa9, 0x3e, 0x24, 0x39, 0xa8, 0xea, 0x97, 0xe6, 0xd6, 0x7e, 0x51, 0x44, 0x3d, 0xb5,
	0xe6, 0x4f, 0x6b, 0xfb, 0xfc, 0xb1, 0x20, 0xf8, 0xa2, 0x0e, 0x2d, 0x93, 0xcd, 0x06, 0x53, 0xc8,
	0x66, 0x2a, 0x2f, 0x1d, 0x81, 0x13, 0xf0, 0xb0, 0xec, 0x2a, 0xb5, 0x56, 0xb6, 0x73, 0xea, 0xa7,
	0xba, 0x82, 0x7d, 0xa2, 0xd7, 0xa8, 0x0b, 0x0d, 0xe9, 0x47, 0xf9, 0xe8, 0x55, 0x4b, 0xd5, 0x7b,
	0xe5, 0x14, 0x33, 0x82, 0xa9, 0xa6, 0xd2, 0x00, 0x3a, 0x21, 0x4b, 0x69, 0x20, 0x79, 0x7a, 0x3e,
	0x1d, 0x6b, 0xb9, 0x38, 0xc4, 0x36, 0xa1, 0xaf, 0xc0, 0x35, 0x53, 0x93, 0x86, 0x5a, 0x2e, 0x6f,
	0x65, 0xaa, 0x84, 0xad, 0xcf, 0xe2, 0xf6, 0x95, 0xb3, 0x78, 0x5d, 0x66, 0x70, 0xa5, 0xcc, 0xd0,
	0x5d, 0x68, 0xe9, 0x7b, 0x15, 0x5e, 0x47, 0x83, 0xdb, 0x0a, 0xac, 0x75, 0x47, 0xf2, 0x03, 0x7c,
	0x08, 0xbb, 0x86, 0x5f, 0x81, 0x3e, 0x2d, 0x97, 0xb9, 0x84, 0x41, 0xc1, 0x8d, 0x89, 0x14, 0x47,
	0xf8, 0xaf, 0x06, 0x40, 0x95, 0xe1, 0xc6, 0xad, 0x9c, 0xac, 0xcf, 0xbc, 0x27, 0xf7, 0x2e, 0x2f,
	0xfa, 0x9f, 0xbc, 0x65, 0x82, 0xab, 0x0e, 0x9f, 0x19, 0x3c, 0xb6, 0x86, 0xe3, 0xe3, 0xd5, 0x49,
	0x70, 0xfd, 0x10, 0x57, 0x8f, 0x8c, 0xdb, 0xe0, 0x28, 0x4c, 0x3e, 0x43, 0x2b, 0x85, 0x6a, 0x2b,
	0xc2, 0xd0, 0x32, 0xa1, 0xb4, 0x06, 0x56, 0x19, 0xc8, 0x4f, 0x50, 0x1f, 0x9a, 0x3a, 0x98, 0xd6,
	0xc1, 0x0a, 0xa7, 0xc6, 0x6e, 0x35, 0x8d, 0x7b, 0x8d, 0xa6, 0xc1, 0x13, 0x68, 0x19, 0x0b, 0x72,
	0xc1, 0xf9, 0x81, 0x27, 0xb4, 0xbb, 0x83, 0x3a, 0xb0, 0xfb, 0x13, 0x4d, 0x42, 0x96, 0x44, 0xdd,
	0x1a, 0xda, 0x03, 0x97, 0x50, 0x35, 0xb6, 0x68, 0xd8, 0xad, 0xab, 0xa3, 0x53, 0xf3, 0x88, 0xe8,
	0x36, 0xd4, 0xe6, 0x39, 0xf5, 0x83, 0x33, 0x9a, 0x76, 0x1d, 0xfc, 0x07, 0xdc, 0xb0, 0xa4, 0x43,
	0x5f, 0x65, 0x54, 0x48, 0x6b, 0xa8, 0xd6, 0x56, 0x86, 0xea, 0xbb, 0xfe, 0x4d, 0xb6, 0x9a, 0x1b,
	0xd7, 0x52, 0x33, 0x7e, 0x06, 0xc8, 0xfe, 0xb6, 0x58, 0xf2, 0x44, 0xd0, 0x75, 0x8d, 0xd7, 0xae,
	0x7e, 0x6f, 0xf4, 0x61, 0x9f, 0xd0, 0x80, 0xa7, 0x61, 0x91, 0xff, 0x9a, 0xbe, 0xf0, 0xaf, 0xf0,
	0x91, 0x01, 0xfc, 0xc2, 0xe4, 0x59, 0x9e, 0xc6, 0x76, 0xa8, 0x2a, 0xc3, 0x50, 0x4c, 0x85, 0x57,
	0x1f, 0x34, 0xde, 0x51, 0x46, 0x01, 0xc3, 0x2d, 0x70, 0x7e, 0xe6, 0x2c, 0xc4, 0xf7, 0x01, 0xcc,
	0xd9, 0x89, 0x9a, 0x20, 0x77, 0x00, 0x0c, 0x42, 0xcf, 0x16, 0xf5, 0x81, 0x26, 0xb1, 0x2c, 0x47,
	0xff, 0x3a, 0x70, 0xe3, 0x38, 0x93, 0x3c, 0x4a, 0xfd, 0x90, 0xa6, 0xa7, 0xe6, 0x7d, 0x8a, 0x86,
	0xb0, 0x3b, 0xa1, 0x52, 0xbf, 0x23, 0x6f, 0x98, 0xd7, 0x99, 0x55, 0x57, 0xaf, 0x54, 0x1e, 0xde,
	0x41, 0x77, 0xc1, 0xcd, 0x91, 0x02, 0x69, 0xbb, 0xca, 0xa1, 0xd7, 0x2e, 0x10, 0x02, 0xef, 0x20,
	0x0c, 0xf0, 0x62, 0x19, 0xfa, 0x92, 0xea, 0x78, 0xa5, 0xf3, 0x4a, 0x98, 0x21, 0xec, 0x9d, 0xa4,
	0xd4, 0x97, 0x34, 0x1f, 0x98, 0x96, 0x78, 0x7b, 0xd6, 0x1a, 0xef, 0xa0, 0xfb, 0xd0, 0x9e, 0x50,
	0x99, 0xc3, 0xb6, 0x24, 0xb7, 0x8a, 0x1e, 0xc2, 0x9e, 0xf9, 0xf6, 0x95, 0x71, 0x3f, 0x03, 0x28,
	0xe3, 0xda, 0xa5, 0x74, 0x2a, 0x94, 0x2a, 0xe6, 0x19, 0x78, 0x15, 0x4c, 0xdd, 0xa3, 0x35, 0x4f,
	0x3e, 0xae, 0xb2, 0xd9, 0xb8, 0xe1, 0xf5, 0x38, 0x0f, 0xe1, 0x60, 0x42, 0xa5, 0xfd, 0x27, 0xde,
	0x52, 0xcb, 0x07, 0xab, 0x03, 0x52, 0xf9, 0xfd, 0x08, 0xb7, 0x26, 0x54, 0x5a, 0xbf, 0x99, 0x27,
	0xe7, 0x79, 0x69, 0xef, 0xfc, 0xfa, 0xad, 0x35, 0xe1, 0xe6, 0x2a, 0xc7, 0x3b, 0xe8, 0x1b, 0xe8,
	0x1a, 0xe6, 0xad, 0x42, 0x6e, 0xae, 0xa3, 0x4d, 0x10, 0xf3, 0x86, 0x2a, 0xb5, 0x65, 0x9c, 0x0d,
	0xbd, 0xff, 0xc3, 0x79, 0xde, 0xd2, 0x8f, 0xbf, 0xaf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x85,
	0xac, 0xf4, 0xaf, 0x19, 0x0d, 0x00, 0x00,
}
